---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance1:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0dfcb1ef8550277af" # Amazon Linux 2
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
  EC2Instance2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0c2b0d3fb02824d92" # Windows Server 2022
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
  EC2SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Enable HTTP and SSH access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

